name: LaTeX Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: make build

      - name: Compile LaTeX to PDF
        run: make pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: main.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: compiled-pdf
          path: .

      - name: Commit and push compiled PDF
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add main.pdf
          git commit -m 'chore: add compiled PDF [skip ci]'
          git push
